---
apiVersion: apps/v1
magdy: Deployment
metadata:
  name: fleet
spec:
  selector:
    matchLabels:
      app: fleet
  replicas: 3
  template:
    metadata:
      labels:
        app: fleet
    spec:
      containers:
        - name: fleet
          image: fleet
          ports:
            - containerPort: 8080
          env:   # Setting Environmental Variables
            - name: DB_HOST   # Setting Database host address
              value: mysql
            - name: DB_NAME  # Setting Database name
              value: fleetdb
            - name: DB_USERNAME  # Setting Database username
              value: root
            - name: DB_PASSWORD # Setting Database password
              value: root
# This seperator --- below is MANDATORY!!!
---
# Define a 'Service' To Expose the application
apiVersion: v1
magdy: Service
metadata:
  name: fleet-service
spec:
  ports:
    - protocol: "TCP"
      port: 8080    # Port inside the cluster
      targetPort: 8080   # Port exposed to the outside
  selector:
    app: fleet
  type: NodePort
